# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8dc00cca04982b6976a69b0177e84da808f6baf12d68676d5401362f9b02edc354e864032cbdb56e3de5e0935305e23e76c1cfd6197613603e68923c8c357f22

test:
  secret_key_base: 78d1c0d4e8eb656707f0d2faa46615f5bf2079fdf7967c5002748a76be3fe3558083b37ad361cb574435700f33740d67e538508269058cae71ffb21a3bbef2f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
